### ISSUE TITLE
# of traits not congruent with json data => leads to wrong ranking

### ISSUE THREAD

**Issue by BarryDB83** [nishantrpai/rarity-score#10]
The collection I have deployed has male and female bases. There are 13 different layer categories but males use 11 and females 10. The json data shows this correctly, they don’t show 'none' for the layers not present.  

Somehow your app shows 13 traits for each NFT. This is not correct. It should only display male or female traits, not both. This leads to wrong ranking.

Any way to disable adding 'missing_traits' in nfts.js?

   https://mtvpunks-mtvtest.vercel.app

**Comment by nishantrpai** [comment]
Currently, the rarity score is calculated this way:

Rarity score of token = rarity of present traits + rarity of missing traits

I don't think it should be disabled, because missing traits is also part of the rarity score calculation i.e., how many other tokens **don't** have this trait.

**Comment by BarryDB83** [comment]
I agree that your method works fine for most collections (tried it on a few), but when there are male/female bases it does give unwanted results. 

Hashlips does have the option to generate multiple sets (with different base folders) and mix them together in 1 lot. In this situation you don’t want the script to behave this way. Males already have a male hat trait, adding female hat ‘none’ doesn’t really make sense here. 

Would you be open to adding an option to turn missing traits on or off?
