### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by moofawsaw** [nishantrpai/rarity-score#3]
When entering `yarn install` into terminal

```
$ husky install
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by nishantrpai** [comment]
Are you running this command in the project folder path @moofawsaw ?

If not,
```
cd *project path*/rarity-score
yarn install
```

**Comment by moofawsaw** [comment]
I am opening the project from Visual Studio and running commands in the terminal. I also tried cd into the folder and yarn install and received the same error.

**Comment by nishantrpai** [comment]
Do check the following things:
0. You are using the remote `https://github.com/nishantrpai/rarity-score.git` or the branch you forked.
1. You are using the `main` branch
2. Do `git pull origin main` to pull the latest changes 
3. Once you are on the `main` branch and pulled the latest files try `yarn install`

Here's a screenshot below, tried to setup locally in a new folder, seems to work for me.

![image](https://user-images.githubusercontent.com/7431166/148886682-7ff8c78a-5a30-477b-8192-4d81b7479bc7.png)

**Comment by moofawsaw** [comment]
I trried from the terminal by installing GitHub CLI Tools then forking like you said and received the same error when running the command `git pull origin main`

```
✓ Logged in as moofawsaw
kyleunderhill@MacBook-Air ~ % gh repo fork https://github.com/nishantrpai/rarity-score.git
✓ Created fork moofawsaw/rarity-score
? Would you like to clone the fork? Yes
Cloning into 'rarity-score'...
remote: Enumerating objects: 629, done.
remote: Counting objects: 100% (629/629), done.
remote: Compressing objects: 100% (456/456), done.
remote: Total 629 (delta 357), reused 426 (delta 160), pack-reused 0
Receiving objects: 100% (629/629), 985.33 KiB | 933.00 KiB/s, done.
Resolving deltas: 100% (357/357), done.
Updating upstream
From https://github.com/nishantrpai/rarity-score
 * [new branch]      main       -> upstream/main
✓ Cloned fork
kyleunderhill@MacBook-Air ~ % git pull origin main
fatal: not a git repository (or any of the parent directories): .git
kyleunderhill@MacBook-Air ~ % 
```

**Comment by moofawsaw** [comment]
I installed it successfully by cloning through Visual Studio. But how do you run the program after I have updated the config file & collection.json?

**Comment by nishantrpai** [comment]
Oops, forgot to add that in the [Readme](https://github.com/nishantrpai/rarity-score/blob/main/README.md)

`yarn run dev` should do it
