### ISSUE TITLE
500 Internal Server Error.

### ISSUE THREAD

**Issue by h0rizons** [nishantrpai/rarity-score#5]
I keep getting 500 internal server error whenever i deploy the template the change my settings.

https://rarityv2.vercel.app/

Any help would be greatly appreciated!

**Comment by nishantrpai** [comment]
Could you provide more details @h0rizons ?

**Comment by nishantrpai** [comment]
vercel console logs or some error when you run locally would be helpful.

**Comment by nishantrpai** [comment]
does anyone else still have this issue?

**Comment by h0rizons** [comment]
I'm not getting the error anymore!

**Comment by h0rizons** [comment]
I messaged you on Twitter, I swapped my metadata out, got it hosted, but I can't this collection to show up locally or on vercel.

I'm not sure if it has something to do with the metadata?

https://coffeerarity.vercel.app/

**Comment by nishantrpai** [comment]
issue resolved.
