### ISSUE TITLE
Setting STARTING_INDEX = 1 throws off NFT detail

### ISSUE THREAD

**Issue by krew-xyz** [nishantrpai/rarity-score#6]
When I set `STARTING_INDEX = 1`, the NFT image that's displayed on the initial screen is not the one that shows when it's clicked and the NFT detail appears. It looks like it's always pulling the next sequential number, not the one that's expected. So if the thumbnail of #200 is clicked, #201 appears in the detail screen.

My collection does starts at ID 1, not 0, did I miss some other setting?

**Comment by nishantrpai** [comment]
The "id" for each item in the collection SHOULD start from 0, the name for that item can start from 1 (in which case you set STARTING_INDEX = 1) for e.g, 

If it's:
```
{ name: "XYZ #1",
   id: 0
 }
 ``` 
 
In this case you set STARTING_INDEX  = 1

If it's:
```
{ name: "XYZ #0",
   id: 0
 }
 ``` 

You set STARTING_INDEX = 0

Does that help?

**Comment by krew-xyz** [comment]
@nishantrpai The collection does not start at #0, it starts at #1. Are you saying I'd have to manually renumber all IDs?

**Comment by nishantrpai** [comment]
It `id` must start from 0. This is a standard in metadata collection, check any opensea collection.

Here's an example: https://opensea.io/assets/ethereum/0xbf93edc8785c33922e9a908abe177d63fc9f8a24/0

id = 0,
Name = Larp Island #1

I'm not sure how you are going to resolve, you could do manually or resolve through a script, depends on your JSON.

This is not a project issue, closing it.

**Comment by krew-xyz** [comment]
I have not found this to be true at all, or even have an ID in their metadata (see Gutter Cat Gang). I have yet to see any main collection start at token ID #0.

**Comment by nishantrpai** [comment]
https://opensea.io/assets/ethereum/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/0

**Comment by krew-xyz** [comment]
https://opensea.io/assets/ethereum/0x19b86299c21505cdf59ce63740b240a9c822b5e4/1
https://opensea.io/assets/ethereum/0xedb61f74b0d09b2558f1eeb79b247c1f363ae452/1

Looks like I'll have to find another solution. Thanks for your time.

**Comment by nishantrpai** [comment]
Code has been updated, you can use whatever id you want in your data.

**Comment by nishantrpai** [comment]
This should close the issue now.

**Comment by nishantrpai** [comment]
https://twitter.com/_rarityscore/status/1538789776371097603
