### ISSUE TITLE
Better handling of large file downloads?

### ISSUE THREAD

**Issue by krew-xyz** [nishantrpai/rarity-score#7]
My NFT collection consists of large NFT files, so when the page loads it's extremely slow and/or images never actually load (even more so when filtering). Do you have any recommendations for handling this e.g progressive loading, preloading, or at least blurred placeholders?

**Comment by krew-xyz** [comment]
Tried implementing this and it seems to help, but not sure I did it 100% correctly:

https://github.com/sconstantinides/react-preload-image

**Comment by BarryDB83** [comment]
Are your images on IPFS? I see the problem you describe on almost all NFT ranking sites. Isn't it just IPFS that's slow? You could try to upload your images to a private server.

**Comment by krew-xyz** [comment]
@BarryDB83 The assets are currently on a centralized private server.

**Comment by nishantrpai** [comment]
The app is simply a client to these URLs, can't introduce caching and other things, although vercel does do it. Initial loads are slow.

**Comment by nishantrpai** [comment]
I'll look into it, I think this is an issue I need to resolve in general anyway.

**Comment by krew-xyz** [comment]
@nishantrpai Awesome! As I mentioned I do have this implemented right now:

https://github.com/sconstantinides/react-preload-image

...and with lazy loading enabled it's definitely better than nothing.

**Comment by nishantrpai** [comment]
Yeah, it is not just the images. Loading the JSON is also slow, so I have been thinking of fixing those. 

Closing this issue for now, will come back to this later.
