### ISSUE TITLE
Husky - pre-commit hook exited with code 1 (error)

### ISSUE THREAD

**Issue by krew-xyz** [nishantrpai/rarity-score#8]
Getting this error when trying to push after a commit all of the sudden. I have to use `git commit -m "message" --no-verify` to force the commit and then push. Here's my package.json:
<img width="382" alt="Screen Shot 2022-06-27 at 2 08 19 PM" src="https://user-images.githubusercontent.com/101286653/176007371-2ac69a61-127a-4f9b-ae4f-7b70604b3018.png">
.

**Comment by nishantrpai** [comment]
Try deleting and installing node_modules?

**Comment by krew-xyz** [comment]
Yeah, I did that a bunch of times, same issue.

**Comment by nishantrpai** [comment]
What is the error btw, there is no screenshot of that.

**Comment by krew-xyz** [comment]
Ah, sorry about that. This was one of them:
<img width="366" alt="Screen Shot 2022-06-27 at 2 07 13 PM" src="https://user-images.githubusercontent.com/101286653/176999257-d040dc62-1bd0-44b1-a6ae-4b8802c2b86b.png">
